---
- name: install imagemagick
  apt:
    pkg: "imagemagick"

- name: configure uwsgi/loris
  template:
    src: "loris2.ini.j2"
    dest: "/etc/loris2/loris2.ini"
    owner: loris
    group: loris
    mode: 0440
  notify: restart uwsgi/loris service

- name: configure uwsgi/loris service
  template:
    src: "loris.service.j2"
    dest: "/etc/systemd/system/loris.service"
    mode: 0644
  notify: restart uwsgi/loris service

- name: create dm user
  user:
    name: "dm"
    group: "www-data"
    comment: "DM"
    shell: /bin/bash

- name: copy DM jar
  copy:
    src: "{{dm_jar_path}}/{{ dm_jar }}"
    dest: "/home/dm/{{ dm_jar }}"
    owner: "dm"
    group: "www-data"
    mode: 0640
  notify: restart DM service

- name: configure DM service
  template:
    src: "dm.service.j2"
    dest: "/etc/systemd/system/dm.service"
    mode: 0644
  notify: restart DM service
