---
- name: install 4store RDF store
  apt: pkg={{item}}
  with_items:
    - 4store
    - libnet-http-perl
    - liburi-perl

- name: create 4store data dir
  file: dest=/var/lib/4store state=directory owner=fourstore group=fourstore mode=0755

- name: create DM knowledge base
  command: 4s-backend-setup dm creates=/var/lib/4store/dm/metadata.nt
  sudo: yes
  sudo_user: fourstore
  notify: restart 4store

- name: make DM knowledge base the default
  lineinfile: dest=/etc/default/4store regexp="^KB=" line="KB=dm"
  notify: restart 4store
