---
- name: install app infrastructure (git etc.)
  apt: pkg={{ item }}
  with_items:
    - git-core
    - python-pip
    - python-dev
    - libjpeg-dev
    - libjpeg8-dev
    - gunicorn

- name: install Python dependencies of app
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    - { name: "django", version: "1.5.4" }
    - { name: "django-haystack", version: "2.3.1" }
    - { name: "south", version: "0.8.2" }
    - { name: "beautifulsoup4", version: "4.3.2" }
    - { name: "html5lib", version: "0.95" }
    - { name: "isodate", version: "0.5.0" }
    - { name: "Pillow", version: "2.6.1" }
    - { name: "pyparsing", version: "2.0.3" }
    - { name: "requests", version: "2.2.1" }
    - { name: "six", version: "1.8.0" }
    - { name: "SPARQLWrapper", version: "1.7.6" }
    - { name: "SQLAlchemy", version: "0.9.4" }

- name: django - configure app
  template: src=app-settings_local.py.j2 dest=/dm/settings_local.py owner=vagrant group=vagrant

- name: django - collect static resources
  django_manage: app_path=/dm command=collectstatic
  become: yes
  become_user: vagrant

- name: django - sync database
  django_manage: app_path=/dm command=syncdb
  become: yes
  become_user: vagrant

- name: django - migrate database
  django_manage: app_path=/dm command=migrate
  become: yes
  become_user: vagrant

- name: configure gunicorn
  template: src=gunicorn-dm.j2 dest=/etc/gunicorn.d/dm
  notify: restart gunicorn

- name: configure nginx
  template: src=nginx-dm.conf.j2 dest=/etc/nginx/conf.d/dm.conf
  notify: restart nginx
