---
- name: install git
  apt:
    pkg: "git-core"
    state: "latest"

- name: install imagemagick
  apt:
    pkg: "imagemagick"
    state: "latest"

- name: create dm user
  user: name=dm comment="DM" shell=/bin/bash

- name: install upstart job
  template:
    src: "templates/init-dm.conf.j2"
    dest: "/etc/init/dm.conf"
  notify: restart dm

- name: checkout sources from GitHub
  git:
    repo: "https://github.com/performant-software/DM.git"
    dest: "/home/dm/app"
    version: "develop"
    depth: 2
    accept_hostkey: True
  become: True
  become_user: dm
  register: git_checkout

- name: stop dm for (re-)build
  service: name=dm state=stopped
  when: git_checkout|changed

- name: build backend
  command: mvn clean package
  args:
    chdir: "/home/dm/app"
    creates: "/home/dm/app/target/dm-{{ dm_version }}.jar"
  become: True
  become_user: dm
  when: git_checkout|changed
  notify: restart dm

- name: configure nginx
  template: src=nginx-dm.conf.j2 dest=/etc/nginx/conf.d/dm.conf
  notify: restart nginx
